python3 ../detect.py \
--weights /home/osense-office/Documents/ext_repo/yolov5/runs/exp23/weights/best.pt \
--source_type video \
--img-size 3000 \
--source /home/osense-office/Desktop/camera/ffmpeg_214_2020-10-15_15-20-00.mp4 \
--output /home/osense-office/Desktop/test \
--device 0 \
--classes 0 \
--conf-thres 0.45 \
--iou-thres 0.4 \
--delay 20 \
--stream_scale 0.4 \
--rotate 1 \
--view-bbox \
--view-dmap \
--save-bbox \
--save-rotate